AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/*'
    - 'db/data/*'
    - 'db/migrate/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/support/*'
    - 'spec/system/**/*'
    - 'node_modules/**/*'
    - 'lib/**/*'
    - 'config/initializers/*'
