version: '3'
services:
  app: &app_base
    env_file: .env
    image: chat_app_development
    build:
      context: .
      args:
        - YARN_INSTALL=1
        - ADDITIONAL_PACKAGES=chromium chromium-chromedriver
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
      - RAILS_LOG_TO_STDOUT=1
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - .:/app
  web:
    image: chat_web_development
    build:      
      context: .      
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 80:80
    depends_on:      
      - app
    volumes:
      - .:/app
  db:
    image: postgres:10.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
volumes:
  db-data:
  redis-data:
